/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ar.edu.uncuyo.view;

import ar.edu.uncuyo.dao.*;
import ar.edu.uncuyo.model.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo
 */
public class clienteJFrame extends javax.swing.JFrame {

    /**
     * Creates new form clienteJFrame
     */
    public clienteJFrame() {
        initComponents();
        setTitle("Gestión de Clientes");
        setLocationRelativeTo(null); // Centrar la ventanita
        cargarTablaClientes();
    }
    
    private void cargarTablaClientes() {
        String[] columnas = {"ID", "Nombre", "Apellido", "DNI", "Teléfono", "Email", "Género"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        clienteDAO dao = new clienteDAO();
        List<cliente> lista = dao.getAllClientes();

        for (cliente c : lista) {
            Object[] fila = {
                c.getId(),
                c.getNombre(),
                c.getApellido(),
                c.getDni(),
                c.getTelefono(),
                c.getEmail(),
                c.getGenero()
            };
            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modificaClienteButton = new javax.swing.JButton();
        CargarClienteButton = new javax.swing.JButton();
        EliminarClienteButton = new javax.swing.JButton();
        volverButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        modificaClienteButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        modificaClienteButton.setText("Modificar cliente");
        modificaClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaClienteButtonActionPerformed(evt);
            }
        });

        CargarClienteButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        CargarClienteButton.setText("Cargar Cliente");
        CargarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarClienteButtonActionPerformed(evt);
            }
        });

        EliminarClienteButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        EliminarClienteButton.setText("Eliminar Cliente");
        EliminarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteButtonActionPerformed(evt);
            }
        });

        volverButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        volverButton1.setText("VOLVER");
        volverButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CargarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(modificaClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(EliminarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(volverButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificaClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CargarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificaClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaClienteButtonActionPerformed
        clienteModificarFormPanel formPanel = new clienteModificarFormPanel();
        this.dispose(); 
        formPanel.setVisible(true);
        formPanel.setLocationRelativeTo(this); // Centrar el formulario
    }//GEN-LAST:event_modificaClienteButtonActionPerformed

    private void CargarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarClienteButtonActionPerformed
        clienteFormPanel formPanel = new clienteFormPanel();
        this.dispose(); 
        formPanel.setVisible(true);
        formPanel.setLocationRelativeTo(this); // Centrar el formulario
    }//GEN-LAST:event_CargarClienteButtonActionPerformed

    private void volverButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton1ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_volverButton1ActionPerformed


    private void EliminarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setContentPane(new clienteFormBajaPanel(this));
        this.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clienteJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarClienteButton;
    private javax.swing.JButton EliminarClienteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificaClienteButton;
    private javax.swing.JButton volverButton1;
    // End of variables declaration//GEN-END:variables
}
